// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: nats/v1/message.proto

package nats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message is a struct used for communication via nats broker/jetstream.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`                          // ts represents creation time.
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                          // id is a uuid of the message.
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // trace_id is an id of a trace (randomly generated if not provided).
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                // payload is the message content.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_nats_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_nats_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_nats_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_nats_v1_message_proto protoreflect.FileDescriptor

const file_nats_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x15nats/v1/message.proto\x12\anats.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n" +
	"\aMessage\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayloadB\aZ\x05nats/b\x06proto3"

var (
	file_nats_v1_message_proto_rawDescOnce sync.Once
	file_nats_v1_message_proto_rawDescData []byte
)

func file_nats_v1_message_proto_rawDescGZIP() []byte {
	file_nats_v1_message_proto_rawDescOnce.Do(func() {
		file_nats_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nats_v1_message_proto_rawDesc), len(file_nats_v1_message_proto_rawDesc)))
	})
	return file_nats_v1_message_proto_rawDescData
}

var file_nats_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nats_v1_message_proto_goTypes = []any{
	(*Message)(nil),               // 0: nats.v1.Message
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_nats_v1_message_proto_depIdxs = []int32{
	1, // 0: nats.v1.Message.ts:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nats_v1_message_proto_init() }
func file_nats_v1_message_proto_init() {
	if File_nats_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nats_v1_message_proto_rawDesc), len(file_nats_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nats_v1_message_proto_goTypes,
		DependencyIndexes: file_nats_v1_message_proto_depIdxs,
		MessageInfos:      file_nats_v1_message_proto_msgTypes,
	}.Build()
	File_nats_v1_message_proto = out.File
	file_nats_v1_message_proto_goTypes = nil
	file_nats_v1_message_proto_depIdxs = nil
}
